    class bullet_impact_helmet_01_wave
	{
		name="bullet_impact_helmet_01_wave";
		sound[]=
		{
			"x\swift\addons\interaction_sfx\data\sounds\death\bullet_impact_helmet_01_wave.wav",
			1.5848932,
			1
		};
		titles[]={};
	};
	class bullet_impact_helmet_02_wave
	{
		name="bullet_impact_helmet_02_wave";
		sound[]=
		{
			"x\swift\addons\interaction_sfx\data\sounds\death\bullet_impact_helmet_02_wave.wav",
			1.5848932,
			1
		};
		titles[]={};
	};
	class bullet_impact_helmet_03_wave
	{
		name="bullet_impact_helmet_03_wave";
		sound[]=
		{
			"x\swift\addons\interaction_sfx\data\sounds\death\bullet_impact_helmet_03_wave.wav",
			1.5848932,
			1
		};
		titles[]={};
	};
    class body_impact_01
    {
        name="body_impact_01";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\body_impact_01.wav",
            1.7782794,
            1
        };
        titles[]={};
    };
    class body_impact_02
    {
        name="body_impact_02";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\body_impact_02.wav",
            1.7782794,
            1
        };
        titles[]={};
    };
    class body_impact_03
    {
        name="body_impact_03";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\body_impact_03.wav",
            1.7782794,
            1
        };
        titles[]={};
    };
    class body_impact_04
    {
        name="body_impact_04";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\body_impact_04.wav",
            1.7782794,
            1
        };
        titles[]={};
    };
        class body_fall_01_wave
    {
        name="body_fall_01_wave";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\body_fall_01_wave.wav",
            1.5848932,
            1
        };
        titles[]={};
    };
    class body_fall_02_wave
    {
        name="body_fall_02_wave";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\body_fall_02_wave.wav",
            1.5848932,
            1
        };
        titles[]={};
    };
    class body_fall_03_wave
    {
        name="body_fall_03_wave";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\body_fall_03_wave.wav",
            1.5848932,
            1
        };
        titles[]={};
    };
    class body_fall_04_wave
    {
        name="body_fall_04_wave";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\body_fall_04_wave.wav",
            1.5848932,
            1
        };
        titles[]={};
    };
    class dob_scream_1
    {
        name="dob_scream_1";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\dob_scream_1.ogg",
            1.9952624,
            1
        };
        titles[]={};
    };
    class dob_scream_2
    {
        name="dob_scream_2";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\dob_scream_2.ogg",
            1.9952624,
            1
        };
        titles[]={};
    };
    class dob_scream_3
    {
        name="dob_scream_3";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\dob_scream_3.ogg",
            1.9952624,
            1
        };
        titles[]={};
    };
    class dob_scream_4
    {
        name="dob_scream_4";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\dob_scream_4.ogg",
            1.9952624,
            1
        };
        titles[]={};
    };
    class dob_scream_5
    {
        name="dob_scream_5";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\dob_scream_5.ogg",
            1.9952624,
            1
        };
        titles[]={};
    };
    class dob_scream_6
    {
        name="dob_scream_6";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\dob_scream_6.ogg",
            1.9952624,
            1
        };
        titles[]={};
    };
    class dob_scream_7
    {
        name="dob_scream_7";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\dob_scream_7.ogg",
            1.9952624,
            1
        };
        titles[]={};
    };
    class dob_scream_8
    {
        name="dob_scream_8";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\dob_scream_8.ogg",
            1.9952624,
            1
        };
        titles[]={};
    };
    class dob_scream_9
    {
        name="dob_scream_9";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\dob_scream_9.ogg",
            1.9952624,
            1
        };
        titles[]={};
    };
    class dob_scream_10
    {
        name="dob_scream_10";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\dob_scream_10.ogg",
            1.9952624,
            1
        };
        titles[]={};
    };
    class dob_scream_11
    {
        name="dob_scream_11";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\dob_scream_11.ogg",
            1.9952624,
            1
        };
        titles[]={};
    };
    class suffocation_4
    {
        name="suffocation_4";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\suffocation_4.ogg",
            1.9952624,
            1
        };
        titles[]={};
    };
    class suffocation_5
    {
        name="suffocation_5";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\suffocation_5.ogg",
            1.9952624,
            1
        };
        titles[]={};
    };
    class suffocation_6
    {
        name="suffocation_6";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\suffocation_6.ogg",
            1.9952624,
            1
        };
        titles[]={};
    };
    class suffocation_7
    {
        name="suffocation_7";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\suffocation_7.ogg",
            1.9952624,
            1
        };
        titles[]={};
    };
    class suffocation_8
    {
        name="suffocation_8";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\suffocation_8.ogg",
            1.9952624,
            1
        };
        titles[]={};
    };
    class suffocation_9
    {
        name="suffocation_9";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\suffocation_9.ogg",
            1.9952624,
            1
        };
        titles[]={};
    };
    class death_1
    {
        name="death_1";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_1.ogg",
            1.1220185,
            1
        };
        titles[]={};
    };
    class death_2
    {
        name="death_2";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_2.ogg",
            1.1220185,
            1
        };
        titles[]={};
    };
    class death_3
    {
        name="death_3";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_3.ogg",
            1.1220185,
            1
        };
        titles[]={};
    };
    class death_4
    {
        name="death_4";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_4.wav",
            1.1220185,
            1
        };
        titles[]={};
    };
    class death_5
    {
        name="death_5";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_5.ogg",
            1.1220185,
            1
        };
        titles[]={};
    };
    class death_6
    {
        name="death_6";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_6.ogg",
            1.1220185,
            1
        };
        titles[]={};
    };
    class death_7
    {
        name="death_7";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_7.ogg",
            1.1220185,
            1
        };
        titles[]={};
    };
    class death_8
    {
        name="death_8";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_8.ogg",
            1,
            1
        };
        titles[]={};
    };
    class death_9
    {
        name="death_9";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_9.wav",
            1,
            1
        };
        titles[]={};
    };
    class death_10
    {
        name="death_10";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_10.wav",
            1,
            1
        };
        titles[]={};
    };
    class death_11
    {
        name="death_11";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_11.wav",
            1,
            1
        };
        titles[]={};
    };
    class death_12
    {
        name="death_12";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_12.ogg",
            1,
            1
        };
        titles[]={};
    };
    class death_13
    {
        name="death_13";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_13.ogg",
            1,
            1
        };
        titles[]={};
    };
    class death_14
    {
        name="death_14";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_14.ogg",
            1,
            1
        };
        titles[]={};
    };
    class death_15
    {
        name="death_15";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_15.ogg",
            1,
            1
        };
        titles[]={};
    };
    class death_16
    {
        name="death_16";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_16.ogg",
            1,
            1
        };
        titles[]={};
    };
    class death_17
    {
        name="death_17";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_17.ogg",
            1.4125376,
            1
        };
        titles[]={};
    };
    class death_18
    {
        name="death_18";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_18.ogg",
            1.4125376,
            1
        };
        titles[]={};
    };
    class death_19
    {
        name="death_19";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_19.ogg",
            1.4125376,
            1
        };
        titles[]={};
    };
    class death_20
    {
        name="death_20";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_20.ogg",
            1.4125376,
            1
        };
        titles[]={};
    };
    class death_21
    {
        name="death_21";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_21.ogg",
            1.4125376,
            1
        };
        titles[]={};
    };
    class death_22
    {
        name="death_22";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_22.ogg",
            1.4125376,
            1
        };
        titles[]={};
    };
    class death_23
    {
        name="death_23";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_23.ogg",
            1,
            1
        };
        titles[]={};
    };
    class death_24
    {
        name="death_24";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_24.ogg",
            1,
            1
        };
        titles[]={};
    };
    class death_25
    {
        name="death_25";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_25.ogg",
            1,
            1
        };
        titles[]={};
    };
    class stealh_scream1
    {
        name="stealh_scream1";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\stealh_scream1.ogg",
            1.1220185,
            1
        };
        titles[]={};
    };
    class stealh_scream2
    {
        name="stealh_scream2";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\stealh_scream2.ogg",
            1.1220185,
            1
        };
        titles[]={};
    };
    class stealh_scream3
    {
        name="stealh_scream3";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\stealh_scream3.ogg",
            1.1220185,
            1
        };
        titles[]={};
    };
    class stealh_scream4
    {
        name="stealh_scream4";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\stealh_scream4.ogg",
            1.1220185,
            1
        };
        titles[]={};
    };
    class stealh_scream5
    {
        name="stealh_scream5";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\stealh_scream5.ogg",
            1.1220185,
            1
        };
        titles[]={};
    };
    class stealh_scream6
    {
        name="stealh_scream6";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\stealh_scream6.ogg",
            1.1220185,
            1
        };
        titles[]={};
    };
    class stealh_scream7
    {
        name="stealh_scream7";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\stealh_scream7.wav",
            1.4125376,
            1
        };
        titles[]={};
    };
    class stealh_scream8
    {
        name="stealh_scream8";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\stealh_scream8.wav",
            1.4125376,
            1
        };
        titles[]={};
    };
    class stealh_scream9
    {
        name="stealh_scream9";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\stealh_scream9.wav",
            1.4125376,
            1
        };
        titles[]={};
    };
    class death_Inside_building_1
    {
        name="death_Inside_building_1";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_Inside_building_1.ogg",
            3.9810717,
            1
        };
        titles[]={};
    };
    class death_Inside_building_2
    {
        name="death_Inside_building_2";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_Inside_building_2.ogg",
            3.9810717,
            1
        };
        titles[]={};
    };
    class death_Inside_building_3
    {
        name="death_Inside_building_3";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_Inside_building_3.ogg",
            3.9810717,
            1
        };
        titles[]={};
    };
    class death_Inside_building_4
    {
        name="death_Inside_building_4";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_Inside_building_4.ogg",
            3.9810717,
            1
        };
        titles[]={};
    };
    class death_Inside_building_5
    {
        name="death_Inside_building_5";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_Inside_building_5.ogg",
            3.9810717,
            1
        };
        titles[]={};
    };
    class death_Inside_building_6
    {
        name="death_Inside_building_6";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_Inside_building_6.ogg",
            3.9810717,
            1
        };
        titles[]={};
    };
    class death_Inside_building_7
    {
        name="death_Inside_building_7";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_Inside_building_7.ogg",
            3.9810717,
            1
        };
        titles[]={};
    };
    class death_Inside_building_8
    {
        name="death_Inside_building_8";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_Inside_building_8.ogg",
            3.9810717,
            1
        };
        titles[]={};
    };
    class death_Inside_building_9
    {
        name="death_Inside_building_9";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_Inside_building_9.ogg",
            3.9810717,
            1
        };
        titles[]={};
    };
    class death_Inside_building_10
    {
        name="death_Inside_building_10";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_Inside_building_10.ogg",
            3.9810717,
            1
        };
        titles[]={};
    };
    class death_Inside_building_11
    {
        name="death_Inside_building_11";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_Inside_building_11.ogg",
            3.9810717,
            1
        };
        titles[]={};
    };
    class death_Inside_building_12
    {
        name="death_Inside_building_12";
        sound[]=
        {
            "x\swift\addons\interaction_sfx\data\sounds\death\death_Inside_building_12.ogg",
            3.9810717,
            1
        };
        titles[]={};
    };