	class weapon_draw_01
	{
		name="weapon_draw_01";
		sound[]=
		{
			"x\swift\addons\interaction_sfx\data\sounds\ironsight\weapon_draw_01.wav",
			1.4125376,
			1
		};
		titles[]={};
	};
	class weapon_draw_02
	{
		name="weapon_draw_02";
		sound[]=
		{
			"x\swift\addons\interaction_sfx\data\sounds\ironsight\weapon_draw_02.wav",
			1.4125376,
			1
		};
		titles[]={};
	};
	class weapon_draw_03
	{
		name="weapon_draw_03";
		sound[]=
		{
			"x\swift\addons\interaction_sfx\data\sounds\ironsight\weapon_draw_03.wav",
			1.4125376,
			1
		};
		titles[]={};
	};
	class weapon_holster_01
	{
		name="weapon_holster_01";
		sound[]=
		{
			"x\swift\addons\interaction_sfx\data\sounds\ironsight\weapon_holster_01.wav",
			1.4125376,
			1
		};
		titles[]={};
	};
	class weapon_holster_02
	{
		name="weapon_holster_02";
		sound[]=
		{
			"x\swift\addons\interaction_sfx\data\sounds\ironsight\weapon_holster_02.wav",
			1.4125376,
			1
		};
		titles[]={};
	};
	class weapon_holster_03
	{
		name="weapon_holster_03";
		sound[]=
		{
			"x\swift\addons\interaction_sfx\data\sounds\ironsight\weapon_holster_03.wav",
			1.4125376,
			1
		};
		titles[]={};
	};
	class ironsight_in_01
	{
		name="ironsight_in_01";
		sound[]=
		{
			"x\swift\addons\interaction_sfx\data\sounds\ironsight\ironsight_in_01.wav",
			1.4125376,
			1
		};
		titles[]={};
	};
	class ironsight_out_01
	{
		name="ironsight_out_01";
		sound[]=
		{
			"x\swift\addons\interaction_sfx\data\sounds\ironsight\ironsight_out_01.wav",
			1.4125376,
			1
		};
		titles[]={};
	};
	class ironsight_in_02
	{
		name="ironsight_in_02";
		sound[]=
		{
			"x\swift\addons\interaction_sfx\data\sounds\ironsight\ironsight_in_02.wav",
			1,
			1
		};
		titles[]=
		{
			0,
			""
		};
	};
	class ironsight_out_02
	{
		name="ironsight_out_02";
		sound[]=
		{
			"x\swift\addons\interaction_sfx\data\sounds\ironsight\ironsight_out_02.wav",
			1,
			1
		};
		titles[]=
		{
			0,
			""
		};
	};